name: Run Azure Login with OpenID Connect
on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Start pipeline'
      run: |
        echo "start"

    - name: 'Login to AZ'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Test AZ login'
      run: |
          az account show
          az group list
          pwd

    - name: 'Get Key-vault secret'
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az keyvault secret show --name "ExamplePassword" --vault-name "<your-unique-keyvault-name>" --query "value"