name: Run Azure Login with OpenID Connect
on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Start pipeline'
      run: |
        echo "start"

    - name: 'Login to AZ'
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: 'Test AZ login'
      run: |
          az account show
          az group list
          pwd

    - name: 'Get Key-vault secret'
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "myVault"
        secrets: 'mySecret'
      id: myGetSecretAction